"""Signal data models."""

from datetime import datetime
from decimal import Decimal
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field


class SignalType(str, Enum):
    """Trading signal types."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class Signal(BaseModel):
    """Trading signal generated by a strategy."""

    id: UUID | None = None
    time: datetime
    strategy_id: str
    instrument: str
    signal_type: SignalType
    strength: Decimal = Field(ge=0, le=1, default=Decimal("0.5"))
    reason: str | None = None
    metadata: dict | None = None


class SignalCreate(BaseModel):
    """Request model for creating a signal."""

    time: datetime
    strategy_id: str
    instrument: str
    signal_type: SignalType
    strength: Decimal = Field(ge=0, le=1, default=Decimal("0.5"))
    reason: str | None = None
    metadata: dict | None = None
